/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

use DataWarehouseAnalytics
--Find total customers by countries
select 
    country,
    count(customer_key) as total_customers 
from gold.dim_customers group by country order by total_customers desc;

--Find total customers by gender
select 
    gender,
    count(customer_key) as total_customers
from gold.dim_customers group by gender order by total_customers desc;

--find total product by category
select 
    category,
    count(product_key) as total_product
from gold.dim_products group by category order by total_product desc


--what is the average costs in each category
select 
    category,
    sum(cost) as total_cost,
    avg(cost) as category_avg_cost,
    count(*) as total_product
from gold.dim_products group by category order by total_cost desc

--what is the total revenue generated for each category?
select 
    p.category,
    sum(s.sales_amount) as total_revenue
from gold.fact_sales as s left join gold.dim_products as p 
on s.product_key=p.product_key group by p.category order by total_revenue desc;

select * from gold.fact_sales


--what is the total revenue generated by each customer?
select 
    c.customer_key,
    c.full_name,
    sum(s.sales_amount) as total_revenue
from gold.fact_sales as s left join gold.dim_customers as c
on s.customer_key=c.customer_key group by c.customer_key,c.full_name order by
total_revenue desc;

--what is the distribution of sold items across countries ?

SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

